export const APP_ACTIONS = {
  FETCH_DATA: 'FETCH_DATA',
  FETCH_DATA_RESOLVED: 'FETCH_DATA_RESOLVED',
  FETCH_DATA_RESOLVING: 'FETCH_DATA_RESOLVING',
  FETCH_DATA_ERROR: 'FETCH_DATA_ERROR',
  STORE_MESSAGE: 'STORE_MESSAGE',
  STORE_MESSAGE_RESOLVED: 'STORE_MESSAGE_RESOLVED',
  STORE_MESSAGE_RESOLVING: 'STORE_MESSAGE_RESOLVING',
};
